### PR TITLE
Proxy & Deployment

### PR DESCRIPTION
**Pull request by kzlsakal**

### CODE REVIEW

**Comment by kzlsakal** [comment]
[Host CSS and other assets on S3 (L)](https://trello.com/c/HPt67Mwn/6-host-css-and-other-assets-on-s3-l)

**Comment by kzlsakal** [comment]
[Remove redundant body-parser middleware (XS)](https://trello.com/c/QD4amX8R/8-remove-redundant-body-parser-middleware-xs)

**Comment by kzlsakal** [comment]
[Use proxy middleware (L)](https://trello.com/c/PrkVN07k/3-use-proxy-middleware-l)

**Comment by kzlsakal** [comment]
[Implement New Relic (L)](https://trello.com/c/eTkk3ZcL/4-implement-new-relic-l)

**Comment by kzlsakal** [comment]
[Remove discontinued moreplacestostay script & proxy target (XS)](https://trello.com/c/LmoflGB8/7-remove-discontinued-moreplacestostay-script-proxy-target-xs)

**Review by james-b-olivas — APPROVED** [review]

**Pull request merged**
